apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yml
  - backend-service.yml
  - worker-deployment.yml
  - frontend-deployment.yml
  - frontend-service.yml
  - gateway.yml
  - frontend-route.yml