apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uptime-sentinel

resources:
  - ../../../base/application

images:
  - name: uptime-sentinel-backend
    newTag: local
  - name: uptime-sentinel-frontend
    newTag: local