alertmanager:
  enabled: false

defaultRules:
  create: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      provider:
        folder: Uptime Sentinel
        folderUid: uptime-sentinel
        allowUiUpdates: false
    datasources:
      uid: uptime-sentinel-prometheus
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "300m"
      memory: "512Mi"

prometheus:
  prometheusSpec:
    retention: 3d
    
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
