"""create incidents table

Revision ID: 11166263a2dd
Revises: d4e41a4cb4d7
Create Date: 2026-08-31 13:56:47.280522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11166263a2dd'
down_revision: Union[str, Sequence[str], None] = 'd4e41a4cb4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_check_id', sa.Integer(), nullable=False),
    sa.Column('closing_check_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closing_check_id'], ['check_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opening_check_id'], ['check_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('closing_check_id'),
    sa.UniqueConstraint('opening_check_id')
    )
    op.create_index(op.f('ix_incidents_monitor_id'), 'incidents', ['monitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_monitor_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
