apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - postgres-service.yml
  - postgres-statefulset.yml
  - redis-service.yml
  - redis-deployment.yml
  - app-configmap.yml
  - network-policy.yml