apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uptime-sentinel

resources:
  - ../../../base/application

images:
  - name: uptime-sentinel-frontend
    newName: ghcr.io/1tsiupryk/uptime-sentinel-frontend
    newTag: "0.1.0"
  - name: uptime-sentinel-backend
    newName: ghcr.io/1tsiupryk/uptime-sentinel-backend
    newTag: "0.1.0"
